# Generated by Django 4.0.2 on 2022-02-04 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.CharField(max_length=500)),
                ('tgl_event', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_uuid', models.UUIDField(default=uuid.UUID('0d37c956-ba12-4a33-b903-a846490c6e47'))),
                ('myqrcode', models.ImageField(upload_to='qrcode/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.buatevent')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pesertaevent')),
            ],
        ),
    ]
